<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultRepository extends EntityRepository
{
    /**
     * @param $tourist
     * @param $quiz
     * @return Result[]
     */
    public function getAllByTouristQuiz($tourist, $quiz)
    {
        return $this->findBy(array('tourist' => $tourist, 'quiz' => $quiz));
    }

    /**
     * @param $quiz Quiz
     * @return array|null
     */
    public function getAllByQuizTourist($quiz)
    {

        $query = $this->getEntityManager()
            ->createQuery('
                SELECT t, r FROM AppBundle:Tourist t
                JOIN AppBundle:Result r
                WHERE t.id = :id
            ')->setParameter('id', $id);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
