<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultRepository extends EntityRepository
{
    /**
     * @param $tourist
     * @param $quiz
     * @return Result[]
     */
    public function getAllByTouristQuiz($tourist, $quiz)
    {
        return $this->findBy(array('tourist' => $tourist, 'quiz' => $quiz));
    }
}
