<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TouristRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TouristRepository extends EntityRepository
{
    /**
     * Get a list of all tourists in an office
     *
     * @param $office Office
     * @return Tourist[]
     */
    public function findAllByOffice($office)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('t')
            ->from('AppBundle:Tourist', 't')
            ->join('t.participations', 'p')
            ->join('p.quiz', 'q')
            ->join('q.office', 'o')
            ->where('o = :office')->setParameter('office', $office)
            ->orderBy('p.createdAt', 'DESC')
        ;

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $reference
     * @param $office Office
     * @return array
     */
    public function findByReference($reference, $office = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('t')
            ->from('AppBundle:Tourist', 't')
        ;

        if ($office) {
            $qb->join('t.quizzes', 'q')
                ->join('q.office', 'o')
                ->andWhere('o = :office')->setParameter('office', $office)
            ;
        }

        return $qb
            ->andWhere('t.reference LIKE :reference')->setParameter('reference', '%'.$reference.'%')
            ->orderBy('t.reference', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }
}
