<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param $office Office
     * @return User[]
     */
    public function findAllByOffice($office)
    {
        return $this->findBy(array('office' => $office));
    }
}
